### ISSUE TITLE
Add support for Super Table

### ISSUE THREAD

**Issue by joshangell** [supercool/Pimp-My-Matrix#10]
![screen shot 2015-11-05 at 13 40 41](https://cloud.githubusercontent.com/assets/404219/10969875/e4050c64-83c2-11e5-9ca7-03f922d26b21.png)

**Comment by theskyfloor** [comment]
oooh what does this entail?

**Comment by joshangell** [comment]
Well, right now I haven't looked into it but hopefully it'll be some kind of support for Matrix fields in ST fields.

**Comment by theskyfloor** [comment]
that would be awesome!

**Comment by brettburwell** [comment]
+1 for this!

**Comment by aladrach** [comment]
I was just coming here to request this! This is a must!

**Comment by joshangell** [comment]
Merging with #38
