### ISSUE TITLE
HTML Parse Error on database migration

### ISSUE THREAD

**Issue by tyler-deboer** [supercool/Pimp-My-Matrix#14]
I installed a new version of Craft on a staging server and imported my SQL database in from my .dev local environment (where PMM is working great). Now when I try loading a page I'm getting this error:

`Parse error: syntax error, unexpected '[' in /var/www/html/craft/plugins/pimpmymatrix/services/PimpMyMatrixService.php on line 142`

I'm guessing this had to be because of a database issue, because it asked me to update my database immediately when I went to the Craft Control Panel on the new server after I cloned all the necessary files and imported the database. Any ideas on how to start fresh with PMM? Are there certain DB tables I need to reset and/or delete?

**Comment by joshangell** [comment]
Hmm weird. I'm not totally sure I understand what exactly is going on here but all the tables you need to hunt down are as follows:

* craft_plugins - remove the PMM row
* craft_pimpmymatrix* - remove any tables that start with this
* craft_migrations - remove the rows that mention PMM

Let me know how that goes!

**Comment by joshangell** [comment]
Hey @tyler-deboer any luck with this? Can I close the issue?

**Comment by tyler-deboer** [comment]
I think so yeah! Cleared all the related tables/rows from the database, reinstalled, and everything worked great. Not sure what happened on the migration but it must have been something on my end. Thanks!

**Comment by joshangell** [comment]
No worries, glad you got it sorted :)
