### ISSUE TITLE
The "Group Your Block Types" should be a page not a modal.

### ISSUE THREAD

**Issue by pixeljitsu** [supercool/Pimp-My-Matrix#15]
Personally, I've tons of fields and having to scroll up and down in the "Group Your Block Types" while dragging the fields at the same time is a bit cumbersome.  If this were a full page and not a modal, it would be much easier to manage the fields.

**Comment by joshangell** [comment]
It is a re-sizable modal ...

**Comment by pixeljitsu** [comment]
Duh, didn't see that.
