### ISSUE TITLE
Craft CMS 2.5+ ?

### ISSUE THREAD

**Issue by rubenwebs** [supercool/Pimp-My-Matrix#22]
I wanted to install this plugin, but it says it needs Craft CMS 2.5+ to work.
But crafts latest release is 2.4.2702: http://buildwithcraft.com/updates

Am I missing something?

**Comment by joshangell** [comment]
Craft 2.5 is [currently in beta](http://buildwithcraft.com/beta) and some of the changes in 2.5 have caused a bunch of changes to this plugin that were much needed but do not work in <2.5.

The last release that will work with <2.5 is [2.0.1](https://github.com/supercool/Pimp-My-Matrix/releases/tag/2.0.1).
