### ISSUE TITLE
Can't select text or set cursor in redactor richtext field

### ISSUE THREAD

**Issue by phaetons** [supercool/Pimp-My-Matrix#24]
I can't select text or set cursor in redactor richtext field when pimpmymatrix is enabled and the block has a block field layout. 
If i disable the plugin, it works as excepted.
I am using pimpmymatrix 2.0.1 with Craft 2.4 (2684).
brgrds Stephan

**Comment by joshangell** [comment]
I have just tested 2.0.1 on Craft 2.4.2696 and can’t reproduce - perhaps upgrade that and see if the issue persists?

**Comment by phaetons** [comment]
It can be that the bug just appears, if you have multiple of that blocks added to the entry. But i will see if i can update Craft too.

**Comment by Hepburni** [comment]
Same issue here. Can't select rich text fields on all the tabs that are hidden on load, so all tabs except first.

**Comment by joshangell** [comment]
Aha, thanks for the extra detail - I'll test that.

**Comment by Hepburni** [comment]
Great! :) FYI I'm using the latest beta of craft 2.5 and latest Pimp-My-Matrix

**Comment by joshangell** [comment]
Hopefully this is fixed in ef53dc99ea71a07b8545789513ced635088952b1 - though I still can’t reproduce.

**Comment by joshangell** [comment]
It seems this is limited to Firefox as far as I can tell as well.
