### ISSUE TITLE
Not configured matrix doesn't show block content

### ISSUE THREAD

**Issue by rubenwebs** [supercool/Pimp-My-Matrix#26]
Craft version: 2.4.2726
PimpMyMatrix version: 2.0.1

When I add a block through a matrix field that isn't configured with this plugin, the content of the block isn't visible:
![screen shot 2015-11-26 at 16 50 20](https://cloud.githubusercontent.com/assets/5013717/11426658/d33ecff4-945d-11e5-909a-933382f4d888.png)

But when I add another block of the same type, then they both are visible again:
![screen shot 2015-11-26 at 16 51 27](https://cloud.githubusercontent.com/assets/5013717/11426671/f64ef8e8-945d-11e5-9017-1aaf5aca9418.png)

Another method to get the field content visible again is to collapse and expand the field.

I've tested same things out without this plugin installed and then it works like normal.
Any solution?

**Comment by rubenwebs** [comment]
Do you have a fix for craft version: 2.4.2726 ?
Because I don't want to update to 2.5 yet, with all the bugs that it has right now.

**Comment by joshangell** [comment]
Sorry no I don’t, I don't have the time right now to maintain a stand-alone 2.4 copy sadly - client work is getting the better of me!
