### ISSUE TITLE
500 Error after Install PMM

### ISSUE THREAD

**Issue by davidhellmann** [supercool/Pimp-My-Matrix#31]
Hey,

a little problem. I develop my site currently local but I test it online today and run in 500 Errors. 
After a long time I tried to deactivate all plugins direct in the DB. After this, all fine. 

I test all plugins and when I click on install PMM he gives me without delay a 500 Error and I have no access to the Backend / Frontend. 

Local works all fine. 
Any Ideas?

Newest Craft Version is installed. 

Cheers.

**Comment by davidhellmann** [comment]
Problem fixed… Server PHP Version was on 5.3. 
I switched to 5.6 and now it works.

Cheers

**Comment by joshangell** [comment]
Glad you got it sorted :smile:
