### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by bshoults** [supercool/Pimp-My-Matrix#34]
I'm getting this error on installation of this plugin. The error is below.

```
Parse error: syntax error, unexpected '[' in --pathtofolder-/craft/plugins/pimpmymatrix/services/PimpMyMatrixService.php on line 224
```

I'm using 2.1.2, but tried all of the 2.5 releases. On Craft Pro 2.5.2759

**Comment by joshangell** [comment]
Hmm that’s weird - what version of php are you using?

**Comment by bshoults** [comment]
Looks like I'm on PHP Version 5.3.29

**Comment by joshangell** [comment]
Aha, that may well be the issue. Try upgrading to at least v 5.5: http://plugins.supercooldesign.co.uk/plugin/pimp-my-matrix/docs#requirements
