### ISSUE TITLE
Invisible Matrix fields on popup forms within CP

### ISSUE THREAD

**Issue by epapada** [supercool/Pimp-My-Matrix#37]
Hi! There seems to be a CSS issue with the matrix fields and Pimp My Matrix when viewed an entry with a matrix field is viewed from a popup/modal. The content of the matrix fields disappear and they reappear if you collapse and expand the field again or you move it briefly.

Check this video showing the issue http://screencast.com/t/0wp60NsI.

Running latest Craft and PMM, tested on Chrome (Latest) and Firefox (Latest).

![2016-03-10_0755](https://cloud.githubusercontent.com/assets/7275397/13660829/389759e0-e696-11e5-9402-863cb2c25d67.png)

**Comment by joshangell** [comment]
Ah, good catch - thanks. I'll add this to the ever increasing list of things to do when I manage to make some time to work on this plugin ... which should hopefully be in the few weeks or so.

Cheers!

**Comment by tnerbovik** [comment]
@epapada  just noticed this. Quickfix if you're in a hurry, go to pimpmymatrix.css and comment out: 
```css
.matrix-field .matrixblock .fields {
 -webkit-opacity: 0;
  -moz-opacity: 0;
  opacity: 0;
}
```
Line 68 - 72

@joshangell really nice plugin

**Comment by epapada** [comment]
Thanks @tnerbovik Quickfix is good :+1: My fields are back! :)
