### ISSUE TITLE
Not working for categories

### ISSUE THREAD

**Issue by jamiewade** [supercool/Pimp-My-Matrix#4]
Hi Josh, as you know I am an avid user of this plugin, the only problem I have is that it doesn't seem to group blocks for categories! Apart from that, it's perfect!

**Comment by joshangell** [comment]
Thanks for the feedback Jamie - could you expand a bit more on what you mean? Are you meaning that you want to use Categories instead of manually writing your own groups in the settings page?

**Comment by jamiewade** [comment]
No worries at all. We have a 'Body content' matrix field that is used throughout the backend. PimpMyMatrix groups this fields blocks up nicely, and this works fine when the matrix field is assigned and used on an entry.

The problem comes when I assign the same field to a category. All of the blocks are showing, but they aren't grouped the same way as the same field in an entry.

**Comment by joshangell** [comment]
Aha I see your point now - so to clarify it would be nice if the grouping worked when used on Category Editors as well as the standard Entry Editors.

That actually shouldn't be that hard, I'll try take a look soon!

**Comment by jamiewade** [comment]
That's exactly it! Thanks a lot :smile:

**Comment by joshangell** [comment]
Hey - if you [download the dev branch](https://github.com/supercool/Pimp-My-Matrix/archive/develop.zip) you can see if my quick patch has worked for you...

**Comment by jamiewade** [comment]
Works perfectly for me, thanks again Josh :+1:

**Comment by joshangell** [comment]
Awesome! I'll look at what other editors it could work in as well - thanks for the heads up :smile:
