### ISSUE TITLE
Block Groups Persist

### ISSUE THREAD

**Issue by UnionDesign** [supercool/Pimp-My-Matrix#45]

**Comment by UnionDesign** [comment]
After removing all the block groups (for a matrix field) and disabling and uninstalling the plugin, my entry pages still show a "Blocks" dropdown list instead of the normal inline list of buttons a matrix would normally show on an entry edit page in Craft.

**Comment by UnionDesign** [comment]
I'm an idiot. Spent an hour backing up the fields, dropping the database, reinstalling Craft... etc... before I stumbled upon the fact that this is expected Craft CMS behaviour below a certain window width... the buttons collapse into a drop down. Sorry.

**Comment by joshangell** [comment]
Hey no worries - glad you worked it out :)

**Comment by supercooljames** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ehoDJMq2&#x2F;243-blocks-to-change"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Blocks to change</a>
