### ISSUE TITLE
Responsive Groups

### ISSUE THREAD

**Issue by jbutts-nerdery** [supercool/Pimp-My-Matrix#7]
The group menus do not appear to handle many options or responsive layouts with the current styling. 

Screenshot attached from Chrome:

![screen shot 2015-07-22 at 3 23 43 pm](https://cloud.githubusercontent.com/assets/3858032/8836350/f1bb048e-3085-11e5-8ffd-b6015113663b.png)

Thanks!

**Comment by joshangell** [comment]
Thanks for the Jim - it is something I'm aware of and I have a solution in mind, just not something I've had the time to sit down and implement yet!

**Comment by joshangell** [comment]
Fixed in 8021771da5286bf8d5a5210392adbcde23d4408a
