### ISSUE TITLE
Matrix Groups Reordering

### ISSUE THREAD

**Issue by birdsigh** [supercool/Pimp-My-Matrix#8]
Matrix groups cannot currently be re-ordered. Changing their order and clicking 'Save' does not update the order of the groups. e.g. I add a new matrix group and drag this so it is the first group, after saving changes the order has not been updated. Is this still to be implemented?

**Comment by joshangell** [comment]
Sorry its taken me ages to get back to you - I haven't actually tried re-ordering so you are right, chances are it hasn't been done yet ... one day I do hope to actually go over the outstanding issues on this plugin and fix them all, but right now its unlikely. Feel free to submit a PR :)

**Comment by joshangell** [comment]
This has been fixed in [v2.0](https://github.com/supercool/Pimp-My-Matrix/releases/tag/2.0)
